NiclasOlofsson/MiNET

- README.md
* Adds docs for installing on Linux and troubleshooting info
* [Minor] Fixes a couple of small grammar issues
> Add some installation documentation for Linux

- README.md
World's most trivial PR? :stuck_out_tongue_closed_eyes: 
Sorry, I just noticed it and it's one of those things that I can't forget once I've seen it.
> Fix capitalisation

- src/MiNET/MiNET/Blocks/BlockFactory.cs
- src/MiNET/MiNET/Blocks/TileGrassPathName.cs
- src/MiNET/MiNET/Items/ItemDiamondShovel.cs
- src/MiNET/MiNET/Items/ItemIronShovel.cs
- src/MiNET/MiNET/Items/ItemShovel.cs
- src/MiNET/MiNET/Items/ItemStoneShovel.cs
- src/MiNET/MiNET/Items/ItemWoodenShovel.cs
- src/MiNET/MiNET/MiNET.csproj
At temp 2. 
•Added Diamond shovel
•Added iron shovel
•Added stone shovel
•Added gold shovel
•Added ItemShovel.cs
•Added Grass Path block
Please make any changes that you wish. Yes, I know I still need to add a few more things but I have got the main stuff.
> Added Grass Path Block

- src/MiNET/MiNET/Items/ItemHoe.cs
> Allow hoeing Grass Paths

- src/MiNET/MiNET/HealthManager.cs
- src/MiNET/MiNET/Items/ItemDiamondAxe.cs
- src/MiNET/MiNET/Items/ItemFactory.cs
- src/MiNET/MiNET/Items/ItemGoldAxe.cs
- src/MiNET/MiNET/Items/ItemGoldSword.cs
- src/MiNET/MiNET/Items/ItemIronAxe.cs
- src/MiNET/MiNET/MiNET.csproj
- src/MiNET/MiNET/Player.cs
http://dictionary.reference.com/browse/prickle
> Typo and BroadcastDeathMessage in HealthManager

- src/MiNET/MiNET/Worlds/AnvilWorldProvider.cs
> Fix Trapdoor conversion.

- src/MiNET/MiNET/Items/ItemFactory.cs
Fixed wall sign and post sign!
> Fixed wall sign and post sign!

- src/MiNET/MiNET/MiNET.csproj
Thanks to jose-vm for telling me that I forgot to add the files from
https://github.com/NiclasOlofsson/MiNET/pull/108 to MiNET.csproj.
> Added files to MiNET.csproj

- src/MiNET/MiNET/Worlds/Level.cs
> Fix players not despawning when switching levels.

- src/MiNET/MiNET/LevelEventType.cs
Not complete and I don't think it will ever be. I got all of these from LevelRenderer::levelEvent and other functions in the MCPE disassembly.
> Add more LevelEvents

- src/MiNET/MiNET/Items/ItemCoal.cs
Coal/Charcoal burns for 8 items / 80 seconds. :)
> Fix coal fuel efficiency.

- src/MiNET/MiNET.Service/server.conf
- src/MiNET/MiNET/MiNetServer.cs
Fixed some config typos and other things.
> Typo Fixes

- src/MiNET/MiNET/HealthManager.cs
Contains a perfect implementation of vanilla in-block suffocation.
> Added suffocation damage.

- src/MiNET/MiNET/Entities/Hostile/Blaze.cs
- src/MiNET/MiNET/Entities/Hostile/CaveSpider.cs
- src/MiNET/MiNET/Entities/Hostile/Creeper.cs
- src/MiNET/MiNET/Entities/Hostile/Enderman.cs
- src/MiNET/MiNET/Entities/Hostile/Ghast.cs
- src/MiNET/MiNET/Entities/Hostile/HostileMob.cs
- src/MiNET/MiNET/Entities/Passive/Bat.cs
- src/MiNET/MiNET/Entities/Passive/Chicken.cs
- src/MiNET/MiNET/Entities/Passive/Cow.cs
- src/MiNET/MiNET/Entities/Passive/IronGolem.cs
- src/MiNET/MiNET/Entities/Passive/MushroomCow.cs
- src/MiNET/MiNET/Entities/Passive/Ocelot.cs
- src/MiNET/MiNET/Entities/Passive/PassiveMob.cs
- src/MiNET/MiNET/Entities/Passive/Pig.cs
- src/MiNET/MiNET/Entities/Passive/Rabbit.cs
- src/MiNET/MiNET/Entities/Passive/Sheep.cs
- src/MiNET/MiNET/Entities/Passive/SnowGolem.cs
- src/MiNET/MiNET/Entities/Passive/Squid.cs
- src/MiNET/MiNET/Entities/Passive/Villager.cs
- src/MiNET/MiNET/Entities/Passive/Wolf.cs
- src/MiNET/MiNET/Entities/Vehicles/Boat.cs
- src/MiNET/MiNET/Entities/Vehicles/Minecart.cs
- src/MiNET/MiNET/Entities/Vehicles/Vechicle.cs
> Use EntityType in Mob Constructors.

- src/MiNET/MiNET/Entities/Hostile/CaveSpider.cs
- src/MiNET/MiNET/Entities/Hostile/Enderman.cs
- src/MiNET/MiNET/Entities/Hostile/Ghast.cs
- src/MiNET/MiNET/Entities/Hostile/Herobrine.cs
- src/MiNET/MiNET/Entities/Hostile/MagmaCube.cs
- src/MiNET/MiNET/Entities/Hostile/Silverfish.cs
- src/MiNET/MiNET/Entities/Hostile/Slime.cs
- src/MiNET/MiNET/Entities/Hostile/Spider.cs
- src/MiNET/MiNET/Entities/Hostile/Witch.cs
- src/MiNET/MiNET/Entities/Passive/Bat.cs
- src/MiNET/MiNET/Entities/Passive/Chicken.cs
- src/MiNET/MiNET/Entities/Passive/Cow.cs
- src/MiNET/MiNET/Entities/Passive/IronGolem.cs
- src/MiNET/MiNET/Entities/Passive/MushroomCow.cs
- src/MiNET/MiNET/Entities/Passive/Ocelot.cs
- src/MiNET/MiNET/Entities/Passive/Pig.cs
- src/MiNET/MiNET/Entities/Passive/Rabbit.cs
- src/MiNET/MiNET/Entities/Passive/Sheep.cs
- src/MiNET/MiNET/Entities/Passive/SnowGolem.cs
- src/MiNET/MiNET/Entities/Passive/Squid.cs
- src/MiNET/MiNET/Entities/Passive/Wolf.cs
- src/MiNET/MiNET/HealthManager.cs
Add MaxHealth property to HealthManager, and set the MaxHealth for all entities.
> Entity health

- src/MiNET/MiNET/HealthManager.cs
Properly implemented lava & fire damage with vanilla Minecraft values.
> Added vanilla lava damage

- src/MiNET/MiNET/Blocks/Leaves.cs
> Fix leaves ID.

- src/MiNET/MiNET.Client/MiNetClient.cs
- src/MiNET/MiNET.Test/MinetServerTest.cs
- src/MiNET/MiNET/HealthManager.cs
- src/MiNET/MiNET/MiNetServer.cs
- src/MiNET/MiNET/Player.cs
- src/MiNET/MiNET/Sounds/Sound.cs
- src/MiNET/MiNET/Worlds/Level.cs
- src/MiNET/TestPlugin/CoreCommands.cs
- src/MiNET/TestPlugin/NiceLobby/NiceLobbyPlugin.cs
- src/MiNET/TestPlugin/Pets/PetHealthManager.cs
> Don't use new Mcpe.... use .CreateObject() !!

- src/MiNET/MiNET/Utils/TextUtils.cs
(CenterLine, Center accounts for Bold properly) pre-compiled regex.
> Improve TextUtils

- src/MiNET/MiNET/Net/Package.cs
MCPE no longer requires that you send the amount of updates that you are going to change, hence the current solution broke updating. This can be applied in many other cases too, not just block updates, but I'll leave that up to you :)
> Fixed block updates!

- src/MiNET/MiNET/Worlds/FlatlandWorldProvider.cs
got tired of constantly falling under the world and dying when testing stuff locally
> Fixed spawn point for flat worlds

- src/MiNET/MiNET.Client/MiNetClient.cs
- src/MiNET/MiNET/Net/MCPE Protocol Documentation.md
- src/MiNET/MiNET/Net/MCPE Protocol.cs
- src/MiNET/MiNET/Net/MCPE Protocol.xml
- src/MiNET/MiNET/Net/Package.cs
- added read for extra string in ResourcePackInfos
- fixed wrong type for ResourcePackClientResponse in spec
- MiNET Client will now properly download complete packs with multiple chunks from servers
> Resource pack fixes

- src/MiNET/MiNET.Client/MiNetClient.cs
- src/MiNET/MiNET/Net/MCPE Protocol Documentation.md
- src/MiNET/MiNET/Net/MCPE Protocol.cs
- src/MiNET/MiNET/Net/MCPE Protocol.xml
- src/MiNET/MiNET/Net/Package.cs
- src/MiNET/MiNET/Utils/ResourcePacks.cs
> Fixed writing pack versions in ResourcePackClientResponse

- src/MiNET/MiNET/Entities/World/PrimedTnt.cs
> fix TNT fuse metadata

- src/MiNET/MiNET/Worlds/Level.cs
It is a really small commit fixing a typo i saw while running the server
> Typo in error message

- src/MiNET/MiNET/Blocks/Allow.cs
- src/MiNET/MiNET/Blocks/BlockFactory.cs
- src/MiNET/MiNET/Blocks/Border.cs
- src/MiNET/MiNET/Blocks/Deny.cs
- src/MiNET/MiNET/Entities/Camera.cs
- src/MiNET/MiNET/Items/ItemCamera.cs
- src/MiNET/MiNET/Items/ItemFactory.cs
The features are not correctly implemented yet, but at least it's a a start! 🎉
> Added new blocks (Allow, Border, Deny) and parts of the camera.

- src/MiNET/MiNET/BlockEntities/BlockEntityFactory.cs
- src/MiNET/MiNET/BlockEntities/ShulkerBoxBlockEntity.cs
- src/MiNET/MiNET/Blocks/BlockFactory.cs
- src/MiNET/MiNET/Blocks/IncompleteBlocks.cs
- src/MiNET/MiNET/Blocks/ShulkerBox.cs
- src/MiNET/MiNET/Blocks/UndyedShulkerBox.cs
- src/MiNET/MiNET/InventoryManager.cs
- src/MiNET/MiNET/Worlds/AnvilWorldProvider.cs
All the Factories in MiNET can be overridden in plugins, and BlockEntityFactory shouldn't be an exception!
Also added basic shulker box implementation because why not.
> Added shulker box. Added CustomBlockEntityFactory.

- src/MiNET/MiNET/Blocks/UndyedShulkerBox.cs
- src/MiNET/MiNET/Worlds/AnvilWorldProvider.cs
Beds from PC worlds use int for color
> Fixed beds not loading from PC worlds.

- src/MiNET/MiNET.Client/MiNetClient.cs
- src/MiNET/MiNET/LoginMessageHandler.cs
- src/MiNET/MiNET/Net/MCPE Protocol Documentation.md
- src/MiNET/MiNET/Net/MCPE Protocol.cs
- src/MiNET/MiNET/Net/MCPE Protocol.xml
- src/MiNET/MiNET/Net/McpeAvailableCommands.cs
- src/MiNET/MiNET/Utils/CryptoUtils.cs
These are all kept in separate commits so you can cherry-pick if you prefer.
> 1.6.0.8 updates + some client fixes

- README.md
Resolution of issues #400 and #396
> Updated readme with the Getting Started section wiki link

- src/MiNET/MiNET/Net/McpeText.cs
- src/MiNET/MiNET/Player.cs
- src/MiNET/MiNET/Worlds/Level.cs
- src/MiNET/TestPlugin/NiceLobby/NiceLobbyPlugin.cs
Added needsTranslation and parameters to SendMessage methods.
> Fixed chat messages not working on 1.7

- src/MiNET/MiNET/Player.cs
> Added virtual DropItem method

- src/MiNET/MiNET/Entities/Entity.cs
- src/MiNET/MiNET/HealthManager.cs
- src/MiNET/MiNET/Player.cs
- src/MiNET/TestPlugin/NiceLobby/NiceLobbyPlugin.cs
> Added MaxHearts to attributes

- src/MiNET/MiNET.Client/Startup.cs
- src/MiNET/MiNET.Console/Startup.cs
- src/MiNET/MiNET.ServiceKiller/Emulator.cs
> Fixed #417

- src/MiNET/MiNET/Net/MCPE Protocol Documentation.md
- src/MiNET/MiNET/Net/MCPE Protocol.cs
- src/MiNET/MiNET/Net/MCPE Protocol.xml
- src/MiNET/MiNET/Net/McpeCommandBlockUpdate.cs
- src/MiNET/MiNET/Player.cs
Changed Player.HandleMcpeCommandBlockUpdate to virtual.
> Added fields for McpeCommandBlockUpdate.

- src/MiNET/MiNET/LoginMessageHandler.cs
- src/MiNET/MiNET/Net/MCPE Protocol Documentation.md
- src/MiNET/MiNET/Net/MCPE Protocol.cs
- src/MiNET/MiNET/Net/MCPE Protocol.xml
- src/MiNET/MiNET/Player.cs
- src/MiNET/MiNET/PlayerNetworkSession.cs
Add handler for McpeScriptCustomEventPacket.
> Make some Handle* methods in Player virtual.

- src/MiNET/MiNET/ExperienceManager.cs
- src/MiNET/MiNET/Player.cs
- src/MiNET/MiNET/Plugins/Commands/VanillaCommands.cs
- src/MiNET/MiNET/Worlds/Level.cs
For easier overwriting experience logic in plugins. And also a small fix for AddExperience method.
> Moved experience logic to ExperienceManager

- src/MiNET/MiNET.Client/log4net.xml
- src/MiNET/MiNET.Console/log4net.xml
- src/MiNET/MiNET.Console/server.conf
- src/MiNET/MiNET.ServiceKiller/log4net.xml
- src/MiNET/MiNET/ServerInfo.cs
Added option to show ServerInfo in the console title (ServerInfoInTitle=true in server.conf).
> Added colors to log4net config.

- src/MiNET/MiNET/Net/BedrockMessageHandler.cs
- src/MiNET/MiNET/Net/MCPE Protocol.cs
- src/MiNET/MiNET/Net/Packet.cs
- src/MiNET/MiNET/Player.cs
- src/MiNET/MiNET/Utils/Skins/PersonaPiece.cs
- src/MiNET/MiNET/Utils/Skins/Skin.cs
- src/MiNET/MiNET/Utils/Skins/SkinPiece.cs
This PR aims to implement MCPE Version 1.14.6 changes.
This version is joinable just fine ( just tested with a single client right now ) , I just need to Read that List of Booleans at the End of the PlayerListPacket ( isTrusted )
> Implement Changes for 1.14.6

- src/MiNET/MiNET/Worlds/AnvilWorldProvider.cs
> Fix MobSpawner block entity

- src/MiNET/MiNET/Player.cs
If you open inventory once and close it, then you won't open any of them after that.
> Inventory close fix.
